import { QuotationLineItem } from "../interfaces/quotation.interface";

export const DEFAULT_QUOTATION_ITEMS: QuotationLineItem[] = [
  // Machine Side Items
  {
    description: "Daikin make 11.0 TR Ductable Split Unit, R - 32",
    qty: 4,
    rate: 0,
    total: 0,
    section: "machine_side",
    unit: "No",
  },
  {
    description: "Daikin make 5.5 TR Ductable Split Unit, R - 32",
    qty: 1,
    rate: 0,
    total: 0,
    section: "machine_side",
    unit: "No",
  },
  // Low Side Items
  {
    description: "Installation, Testing & Commissioning & Handing over of 11.0 TR Ducted Split Unit",
    qty: 4,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "No.",
  },
  {
    description: "Installation, Testing & Commissioning & Handing over of 5.5TR Ducted Split Unit",
    qty: 1,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "No.",
  },
  {
    description: "Supply & installation of interconnecting refrigerant copper pipe size approved by OEM company insulated with 9mm thick closed cell electrometric nitrile class O’ type rubber tubular insulation between each set of indoor & outdoor units.",
    qty: 30,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Rmt",
  },
  {
    description: "Supply and installation of 1.0 Sqmm communication cable providing & fixing control cum transmission wiring of OEM suggested size shielded/seathed flexible control cable between indoor & outdoor unit as per the specifications",
    qty: 40,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Rmt",
  },
  {
    description: "Supply and installation of Power cable for Ac machines from the isolator to outdoor unit",
    qty: 15,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Rmt",
  },
  {
    description: "25/32 mm Dia UPVC drain pipe with insulation of – schedule 40 pipe, white in colour, joint properly glued with UPVC adhesive for water outlet from indoor unit. Drain line to the nearest drain as per site condition (32mm)",
    qty: 30,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Rmt",
  },
  {
    description: "R410 A Refrigerant charging (R410A)",
    qty: 5,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Kg",
  },
  {
    description: "Supply,erection of fabricated GSS ducting as per drawing complete with all fttings - 0.63mm GSS ducting",
    qty: 297,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "sqm",
  },
  {
    description: "Supply,erection of fabricated GSS ducting as per drawing complete with all fttings - 0.80mm GSS ducting",
    qty: 49.5,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "sqm",
  },
  {
    description: "Supply & installation of 9mm thick closed cell elastomeric nitrile rubber thermal insulation",
    qty: 297,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "sqm",
  },
  {
    description: "Supply & installation of 10mm thick closed cell elastomeric nitrile rubber acoustic insulation",
    qty: 49.5,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Sqm",
  },
  {
    description: "Supply and fix the Supply Air aluminium powder coated Grills continuos type with Collar damper",
    qty: 10.5,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Sqm",
  },
  {
    description: "Supply and fixing of canvas connection",
    qty: 5,
    rate: 0,
    total: 0,
    section: "low_side",
    unit: "Nos.",
  },
];
